Models/Alocar.cs
using System;

namespace desafio_mvc.Models
{
    public class Alocar
    {
        public int Id {get; set;}
        public Vaga VagaID {get; set;}
        public Funcionario FuncionarioID {get; set;}
        
    }
}

Models/Funcionario.cs
using System;
using System.Collections.Generic;

namespace desafio_mvc.Models
{
    public class Funcionario
    {
        public int Id {get; set;}
        public string Nome {get; set;}
        public string Matricula {get; set;}
        public string Cargo {get; set;}
        public DateTime Inicio_wa {get; set;}
        public DateTime Termino_wa {get; set;}
        public Gft Gft_Id {get; set;}
        public Vaga Vaga_Id {get; set;}
        public bool Status {get; set;}
        public string Level {get; set;}
        public string Foto {get; set;}

        //relacionamento com as tecnologias
        public virtual List<Funcionario_Tecnologia> FuncTecnologia {get; set;}

        // public static implicit operator Funcionario(int v)
        // {
        //     throw new NotImplementedException();
        // }
        //public ICollection<Funcionario_Tecnologia> FuncTecnologia {get; set;}
    }
}

Models/Gft.cs
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.AspNetCore.Http;

namespace desafio_mvc.Models
{
    public class Gft
    {
        public int Id {get; set;}

        public string Cep {get; set;}

        public string Cidade {get; set;}

        public string Endereco {get; set;}

        public string Estado {get; set;}

        public string Nome {get; set;}

        public string Telefone {get; set;}

        public string Foto {get; set;}

        public bool Status {get; set;}
    }
}

Models/Projeto.cs
namespace desafio_mvc.Models
{
    public class Projeto
    {
        public int Id {get; set;}

        public string Nome {get; set;}

        public bool Status {get; set;}

        //talvez eu cloque uma epoca do projeto
    }
}

Models/Tecnologia.cs
using System.Collections.Generic;

namespace desafio_mvc.Models
{
    public class Tecnologia
    {
        public int Id {get; set;}
        public string Nome {get; set;} 

        //relacionameto com vaga e vaga_tecnologia
        public virtual List<Vaga_Tecnologia> VagaTecnologia {get; set;}

        //relacionamento com vaga e funcionario_tecnologia
        public virtual List<Funcionario_Tecnologia> FuncTecnologia {get; set;}
    }
}

Controllers/AlocacaoController.cs
using System;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using desafio_mvc.Data;
using desafio_mvc.DTO;
using desafio_mvc.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Authorization;

namespace desafio_mvc.Controllers
{
    public class AlocacaoController : Controller
    {
        private readonly ApplicationDbContext database;
        public AlocacaoController(ApplicationDbContext database)
        {
            this.database = database;
        }

        public IActionResult Alocar(AlocarDTO aloTemp) //botao de alocar
        {
                var alo = database.Alocars.First(a => a.Id == aloTemp.Id);
            
                //pegar o id de funcionario e guardar sua vaga e seu status
                Funcionario func = new Funcionario();
            
                var func2 = database.Funcionarios.First(f => f.Id == aloTemp.FuncionarioID);
                func2.Vaga_Id = database.Vagas.First(v => v.Id == aloTemp.VagaID);
                func2.Status = false;
                database.SaveChanges();

                //diminuir a quantidade de vagas
                var vaga = database.Vagas.FirstOrDefault(v => v.Id == aloTemp.VagaID);
                vaga.Qtd_vaga = vaga.Qtd_vaga - 1;
                database.SaveChanges();

                
            return RedirectToAction("Alocar", "wa");
        }

        [Authorize(Policy = "TipoAdm")]
        public IActionResult Sugestao()
        {
            Alocar alo = new Alocar();
            //gera sugestoes de possiveis alocacoes
            var funcionarios = database.Funcionarios.Include(t => t.FuncTecnologia).ThenInclude(te => te.Tecnologia).Where(p => p.Status == true).ToList();
            var vagas = database.Vagas.Include(t => t.Tecnologias).ThenInclude(te => te.Tecnologia).Where(p => p.Status == true).ToList();
            foreach (var fun in funcionarios)
            {
                //int funcid = fun.Id;
                foreach (var ftec in fun.FuncTecnologia.Select(f => f.Tecnologia))
                {
                    foreach(var vag in vagas)
                    {
                        //int vagaid = vag.Id;
                        foreach (var vtec in vag.Tecnologias.Select(f => f.Tecnologia))
                        {
                            if(ftec.Nome.ToUpper() == vtec.Nome.ToUpper() && fun.Cargo.ToUpper() == vag.Descricao_vaga.ToUpper())
                            {
                                alo.VagaID = database.Vagas.First(v => v.Id == vag.Id);
                                alo.FuncionarioID = database.Funcionarios.First(f => f.Id == fun.Id);
                                database.Alocars.Add(alo);
                                database.SaveChanges();
                            }
                        }
                    }
                }
            }
            return RedirectToAction("Alocar", "wa");
        }

        [Authorize(Policy = "TipoAdm")]
        public IActionResult Dispensar(int id)
        {
            //dispensar uma sugestao
            Alocar alocar = database.Alocars.First(alo => alo.Id == id);
            database.Alocars.Remove(alocar);
            database.SaveChanges();
            return RedirectToAction("Alocar", "wa");
        }
    }
}

Controllers/FuncionariosController.cs
using System;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using desafio_mvc.Data;
using desafio_mvc.DTO;
using desafio_mvc.Models;
using Microsoft.AspNetCore.Hosting;
using System.IO;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;

namespace desafio_mvc.Controllers
{
    public class FuncionariosController : Controller
    {
        private readonly ApplicationDbContext database;
        private readonly IWebHostEnvironment webHostEnvironment;
        public FuncionariosController(ApplicationDbContext database, IWebHostEnvironment hostEnvironment)
        {
            this.database = database;
            webHostEnvironment = hostEnvironment;
        }

        [HttpPost]
        public async Task<IActionResult> Salvar(FuncionarioDTO funcTemporario)
        {
            if(ModelState.IsValid)
            {
                string nomeArquivo = UploadedFile(funcTemporario);
                Funcionario func = new Funcionario();

                func.Nome = funcTemporario.Nome;
                func.Matricula = funcTemporario.Matricula;
                func.Cargo = funcTemporario.Cargo;
                func.Inicio_wa = funcTemporario.Inicio_wa;
                func.Termino_wa = funcTemporario.Inicio_wa.AddDays(17);
                func.Gft_Id = database.Gfts.First(f => f.Id == funcTemporario.Gft_Id);
                func.Status = true;
                func.Level =  funcTemporario.Level;
                func.Foto = nomeArquivo;

                database.Funcionarios.Add(func);
                await database.SaveChangesAsync();

                Tecnologia tec = new Tecnologia();
                Funcionario_Tecnologia FunTec = new Funcionario_Tecnologia();

                //func.FuncTecnologia = database.Funcionario_Tecnologias.First(f => f.Id == funcTemporario.FuncTecnologia);
                FunTec.Funcionario = database.Funcionarios.First(f => f.Id == func.Id);
                FunTec.Tecnologia = database.Tecnologias.First(t => t.Id == funcTemporario.FuncTecnologia);
                
                database.Funcionario_Tecnologias.Add(FunTec);
                await database.SaveChangesAsync();

                return RedirectToAction("Funcionarios", "wa");
            }
            else{
                return View("../wa/Cadastrar");
            }
        }

        private string UploadedFile(FuncionarioDTO model)
        {
            string nomeArquivo = null;
            if (model.Foto != null)
            {
                string pastaFotos = Path.Combine(webHostEnvironment.WebRootPath, "Imagens2");
                nomeArquivo = Guid.NewGuid().ToString() + "_" + model.Foto.FileName;
                string caminhoArquivo = Path.Combine(pastaFotos, nomeArquivo);
                using (var fileStream = new FileStream(caminhoArquivo, FileMode.Create))
                {
                    model.Foto.CopyTo(fileStream);
                }
            }
            return nomeArquivo;
        }

        [HttpPost]
        public IActionResult Editar(FuncionarioDTO funcTemporario)
        {
            if(ModelState.IsValid)
            {
                var func = database.Funcionarios.First(f => f.Id == funcTemporario.Id);
                func.Nome = funcTemporario.Nome;
                func.Matricula = funcTemporario.Matricula;
                func.Cargo = funcTemporario.Cargo;
                func.Inicio_wa = funcTemporario.Inicio_wa;
                func.Termino_wa = funcTemporario.Inicio_wa.AddDays(17);
                func.Gft_Id = database.Gfts.First(f => f.Id == funcTemporario.Gft_Id);
                func.Level = funcTemporario.Level;
                
                database.SaveChanges();

                Funcionario_Tecnologia FunTec = new Funcionario_Tecnologia();
                FunTec.Funcionario = database.Funcionarios.First(f => f.Id == func.Id);
                FunTec.Tecnologia = database.Tecnologias.First(t => t.Id == funcTemporario.FuncTecnologia);
                
                database.SaveChanges();

                return RedirectToAction("Funcionarios", "wa");
            }
            else{
                return View("../wa/EditarFuncionario");
            }
        }

        [Authorize(Policy = "TipoAdm")]
        public IActionResult Deletar(int id)
        {
            if(id > 0)
            {
                var func = database.Funcionarios.First(f => f.Id == id);
                func.Status = false;
                database.SaveChanges();
            }
            return RedirectToAction("Funcionarios", "wa");
        }
    }
}

Controllers/GftController.cs
using System;
using System.Linq;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using desafio_mvc.Data;
using desafio_mvc.DTO;
using desafio_mvc.Models;
using System.IO;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;

namespace desafio_mvc.Controllers
{
    public class GftController : Controller
    {
        private readonly ApplicationDbContext database;
        private readonly IWebHostEnvironment webHostEnvironment;
        
        public GftController(ApplicationDbContext database, IWebHostEnvironment hostEnvironment)
        {
            this.database = database;
            webHostEnvironment = hostEnvironment;
        }

        [HttpPost]
        public IActionResult Editar(GftDTO gfttemporaria)
        {
            if(ModelState.IsValid)
            {
                var gfts = database.Gfts.First(v => v.Id == gfttemporaria.Id);
                gfts.Nome = gfttemporaria.Nome;
                gfts.Cep = gfttemporaria.Cep;
                gfts.Cidade = gfttemporaria.Cidade;
                gfts.Endereco = gfttemporaria.Endereco;
                gfts.Estado = gfttemporaria.Estado;
                gfts.Telefone = gfttemporaria.Telefone;
                //gfts.Foto = gfttemporaria.Foto;
                database.SaveChanges();
                return RedirectToAction("Gft", "wa");
            }
            else{
                return View("../wa/EditarGft");
            }
            
        }

        [HttpPost]
        [Authorize(Policy = "TipoAdm")]
        public IActionResult Deletar(int id)
        {
            if(id > 0)
            {
                var gft = database.Gfts.First(g => g.Id == id);
                gft.Status = false;
                database.SaveChanges();
            }
            return RedirectToAction("Gft", "wa");
        }

        public async Task<IActionResult> Salvar(GftDTO gfttemporaria)
        {
            if (ModelState.IsValid)
            {
                string nomeUnicoArquivo = UploadedFile(gfttemporaria);
                Gft gfts = new Gft();

                    gfts.Nome = gfttemporaria.Nome;
                    gfts.Cep = gfttemporaria.Cep;
                    gfts.Cidade = gfttemporaria.Cidade;
                    gfts.Endereco = gfttemporaria.Endereco;
                    gfts.Estado = gfttemporaria.Estado;
                    gfts.Telefone = gfttemporaria.Telefone;
                    gfts.Foto = nomeUnicoArquivo;
                    gfts.Status = true;
                
                database.Gfts.Add(gfts);
                await database.SaveChangesAsync();
                return RedirectToAction("Gft", "wa");
            }
            return View("CadastrarGft", "wa");
        }

        private string UploadedFile(GftDTO model)
        {
            string nomeUnicoArquivo = null;
            if (model.Foto != null)
            {
                string pastaFotos = Path.Combine(webHostEnvironment.WebRootPath, "Imagens");
                nomeUnicoArquivo = Guid.NewGuid().ToString() + "_" + model.Foto.FileName;
                string caminhoArquivo = Path.Combine(pastaFotos, nomeUnicoArquivo);
                using (var fileStream = new FileStream(caminhoArquivo, FileMode.Create))
                {
                    model.Foto.CopyTo(fileStream);
                }
            }
            return nomeUnicoArquivo;
        }
    }
}

Controllers/HistoricoController.cs
using System;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using desafio_mvc.Data;
using desafio_mvc.DTO;
using desafio_mvc.Models;

namespace desafio_mvc.Controllers
{
    public class HistoricoController : Controller
    {
        
    }
}

Controllers/ProjetoController.cs
using System;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using desafio_mvc.Data;
using desafio_mvc.DTO;
using desafio_mvc.Models;
using Microsoft.AspNetCore.Authorization;

namespace desafio_mvc.Controllers
{
    public class ProjetoController : Controller
    {
        private readonly ApplicationDbContext database;
        public ProjetoController(ApplicationDbContext database)
        {
            this.database = database;
        }

        [HttpPost]
        public IActionResult Salvar(ProjetoDTO projTemp)
        {
            if(ModelState.IsValid)
            {
                Projeto proj = new Projeto();

                proj.Nome = projTemp.Nome;
                proj.Status = true;

                database.Projetos.Add(proj);
                database.SaveChanges();

                return RedirectToAction("Projetos", "wa");
            }
            else{
                return View("../wa/CadastrarProjeto");
            }
            
        }

        [HttpPost]
        public IActionResult Editar(ProjetoDTO projTemp)
        {
            if(ModelState.IsValid)
            {
                var proj = database.Projetos.First(p => p.Id == projTemp.Id);

                proj.Nome = projTemp.Nome;

                database.SaveChanges();

                return RedirectToAction("Projetos", "wa");
            }
            else{
                return View("../wa/CadastrarProjeto");
            }
        }

        [Authorize(Policy = "TipoAdm")]
        public IActionResult Deletar (int id)
        {
            if(id > 0)
            {
                var proj = database.Projetos.First(p => p.Id == id);
                proj.Status = false;
                database.SaveChanges();
            }
            return RedirectToAction("Projetos", "wa");
        }
    }
}

Controllers/TecnologiaController.cs
using System;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using desafio_mvc.Data;
using desafio_mvc.DTO;
using desafio_mvc.Models;

namespace desafio_mvc.Controllers
{
    public class TecnologiaController : Controller
    {
        private readonly ApplicationDbContext database;
        public TecnologiaController(ApplicationDbContext database)
        {
            this.database = database;
        }

        [HttpPost]
        public IActionResult Salvar(TecnologiaDTO tecTemporario)
        {
            if(ModelState.IsValid)
            {
                Tecnologia tec = new Tecnologia();
                tec.Nome = tecTemporario.Nome;

                database.Tecnologias.Add(tec);
                database.SaveChanges();
                return RedirectToAction("Tecnologia", "wa");
            }
            else{
                return View("../wa/CadastrarTecnologia");
            }
        }
        [HttpPost]
        public IActionResult Editar(TecnologiaDTO tecTemporario)
        {
            if(ModelState.IsValid)
            {
                var tec = database.Tecnologias.First(t => t.Id == tecTemporario.Id);
                tec.Nome = tecTemporario.Nome;

                database.SaveChanges();
                return RedirectToAction("Tecnologia", "wa");
            }
            else{
                return View("../wa/EditarTecnologia");
            }
           
        }
    }
}

Views/wa/Alocar.cshtml
 @model IEnumerable<desafio_mvc.Models.Alocar>

<h2 class="text-center">Sugestões de Alocação</h2>
<hr>
<br>
<a class="btn btn-secondary" asp-action="Sugestao" asp-controller="Alocacao" role="button">Gerar sugestões</a>
<br>
<br>

@foreach (var alo in Model)
{
  @if(alo.FuncionarioID.Status == true)
  {
    <div class="jumbotron">
      @* Esse lado esta o funcionario *@
      <div class="row">
        <div class="col-sm-6"> 
          <h1>@alo.FuncionarioID.Nome</h1>
          <p class="lead">Cargo: @alo.FuncionarioID.Cargo - @alo.FuncionarioID.Level</p>
          <p class="font-weight-bolder">Principal Tecnologia: @foreach (var tec in alo.FuncionarioID.FuncTecnologia.Select(t => t.Tecnologia))
              {
                @tec.Nome
              }
          </p>
          @* <p class="lead">@alo.FuncionarioID.Gft_Id.Nome</p> *@
          <p class="font-weight-lighter">GFT Brasil></p>
          <p class="font-weight-lighter">Matricula: @alo.FuncionarioID.Matricula</p>
          <br>
          <a class="btn btn-dark col-sm-6" href="/wa/PerfilFuncionario/@alo.FuncionarioID.Id">Perfil</a>
        </div>

        @* Esse lado esta a vaga *@
        <div class="col-sm-6">
          <h1>@alo.VagaID.Descricao_vaga</h1>
          @* <p class="font-weight-bolder">Projeto: @alo.VagaID.ProjetoCad.Nome</p> *@
          <p class="font-weight-bolder">Projeto: </p>
          <p class="font-weight-bolder">Principal Tecnologia: @foreach (var tec in alo.VagaID.Tecnologias.Select(t => t.Tecnologia))
              {
                @tec.Nome
              }
          </p>
          <p class="font-weight-lighter">Quantidade: @alo.VagaID.Qtd_vaga vagas</p>
          <p class="font-weight-lighter">Codigo da Vaga: @alo.VagaID.Codigo_vaga</p>
        </div>
      </div>
      

      <hr class="my-4">
      <div class="row">
          <a class="btn btn-primary" href="/wa/CadastrarAlocacao/@alo.Id">Alocar</a> 
          <form asp-action="Dispensar" asp-controller="Alocacao" style="display: inline;">
            <input type="hidden" name="id" id="id" value="@alo.Id">
            <button class="btn btn-danger">Dispensar</button>
          </form>
      </div>
     
     
    </div>
  }
  else{

  }
  
}

Views/wa/Cadastrar.cshtml
@model desafio_mvc.DTO.FuncionarioDTO

<script>
    $(document).ready(function(){
        $("#btnAdd").click(function(){
            $("#listaTec").append("<li>"+$("Tec option:selected").text()+"<input type='checkbox' name='check' id='check' checked='checked' value='"+$("Tec option:selected").val()+"'></li>")
        })
    });
</script>

<h3>Novo Funcionario</h3>
<hr/>

<form id ="funcionario" class="form-horizontal" asp-action="Salvar" asp-controller="Funcionarios" method="POST">
    <input type="hidden" asp-for="Id" value="0">

    <label asp-for="Nome">Nome</label>
    <input type="text" asp-for="Nome" class="form-control" placeholder="Nome do funcionario"><br>
    <span asp-validation-for="Nome"></span>

    <label asp-for="Matricula">Matricula</label>
    <input type="text" asp-for="Matricula" class="form-control" placeholder="533789"><br>
    <span asp-validation-for="Matricula"></span>

    <label asp-for="Cargo">Cargo</label>
    <input type="text" asp-for="Cargo" class="form-control" placeholder="Cargo anterior"><br>
    <span asp-validation-for="Cargo"></span>
    
    <label asp-for="Level">Level</label>
    <select class="form-control" asp-for="Level">
        <option value='L0'>L0</option>
        <option value='L1'>L1</option>
        <option value='L2'>L2</option>
        <option value='L3'>L3</option>
        <option value='L4'>L4</option>
        <option value='L5'>L5</option>
        <option value='L6'>L6</option>
        <option value='L7'>L7</option>
    </select>
    <span asp-validation-for="Level"></span>

    <label asp-for="Inicio_wa">Inicio WA</label>
    <input type="date" asp-for="Inicio_wa" class="form-control"><br>
    <span asp-validation-for="Inicio_wa"></span>

    <label asp-for="Gft_Id">GFT</label>
    <select class="form-control" asp-for="Gft_Id" asp-items='@(new SelectList(@ViewBag.Gfts,"Id","Nome"))'></select>
    <span asp-validation-for="Gft_Id"></span>

    <br>
    <label asp-for="Foto">Foto</label>
    <input type="file" asp-for="Foto" class="form-control-file">
    <span asp-validation-for="Foto" class="text-danger"></span><br>
    <br>

    <label asp-for="FuncTecnologia">Tecnologia</label>
    <select id="Tec" class="form-control" asp-for="FuncTecnologia" asp-items='@(new SelectList(@ViewBag.Tecnologia,"Id","Nome"))'></select>
    <button id="btnAdd" class="btn btn-outline-info">Adicionar</button>
    <br>
    <ul id="listaTec"></ul>
    <br>
    <button class="btn btn-success">Cadastrar</button>
</form> 
<br>
<a asp-action="Funcionarios" asp-controller="wa" class="btn btn-dark">Voltar</a>

Views/wa/CadastrarAlocacao.cshtml
@model desafio_mvc.DTO.AlocarDTO

<div class="text-center">
    <h3>Confirmar Alocação</h3>
    <hr/>
    <form asp-action="Alocar" asp-controller="Alocacao">
        <input type="hidden" asp-for="Id">

        <label asp-for="FuncionarioID">Funcionario</label>
        <select class="form-control" asp-for="FuncionarioID" asp-items='@(new SelectList(@ViewBag.Funcionarios,"Id","Nome"))'></select>
        
        <label asp-for="VagaID">Vaga</label>
        <select class="form-control" asp-for="VagaID" asp-items='@(new SelectList(@ViewBag.Vagas,"Id","Descricao_vaga"))'></select>
        <br>
        <button class="btn btn-success">Finalizar Alocação</button>
    </form>
    <br>
    <a asp-action="Alocar" asp-controller="wa" class="btn btn-dark">Voltar</a>
</div>

Views/wa/CadastrarProjeto.cshtml
@model desafio_mvc.DTO.ProjetoDTO

<h2>Cadastro de um novo projeto</h2>
<hr/>

<form class="form-horizontal" asp-action="Salvar" asp-controller="Projeto" method="POST">
    <input type="hidden" asp-for="Id" value="0">
    
    <label asp-for="Nome">Nome</label>
    <input type="text" asp-for="Nome" class="form-control" placeholder="Nome">
    <span asp-validation-for="Nome" class="text-danger"></span><br>

    <button class="btn btn-success">Cadastrar</button>
</form> 
<br>
<a asp-action="Projetos" asp-controller="wa" class="btn btn-dark">Voltar</a>

Views/wa/EditarProjeto.cshtml
@model desafio_mvc.DTO.ProjetoDTO

<h2>Editar um Projeto</h2>
<hr/>

<form class="form-horizontal" asp-action="Editar" asp-controller="Projeto" method="POST">
    <input type="hidden" asp-for="Id">
    
    <label asp-for="Nome">Nome</label>
    <input type="text" asp-for="Nome" class="form-control" placeholder="Nome">
    <span asp-validation-for="Nome" class="text-danger"></span><br>

    <button class="btn btn-success">Atualizar</button>
</form> 
<br>
<a asp-action="Projetos" asp-controller="wa" class="btn btn-success">Voltar</a>

Views/wa/EditarTecnologia.cshtml
@model desafio_mvc.DTO.TecnologiaDTO;

<h2>Editar Tecnologia</h2>
<hr/>

<form class="form-horizontal" asp-action="Editar" asp-controller="Tecnologia" method="POST">
    <input type="hidden" asp-for="Id">

    <label asp-for="Nome">Nome</label>
    <input type="text" asp-for="Nome" class="form-control" placeholder="Mainframe"><br>
    <span asp-validation-for="Nome"></span>

    <button class="btn btn-success">Atualizar</button>
</form> 
<br>

<a asp-action="Tecnologia" asp-controller="wa" class="btn btn-dark">Voltar</a>

Views/wa/Index.cshtml
<h2 class="text-center">Funções</h2>
<br>

<a asp-action="Funcionarios" asp-controller="wa" class="btn btn-outline-secondary btn-lg btn-block">Funcionarios</a>
<hr/>

<a asp-action="Vagas" asp-controller="wa" class="btn btn-outline-success btn-lg btn-block">Vagas</a>
<hr/>

<a asp-action="Alocar" asp-controller="wa" class="btn btn-outline-info btn-lg btn-block">Alocacao</a>
<hr/>

<a asp-action="Historico" asp-controller="wa" class="btn btn-outline-dark btn-lg btn-block">Historico</a>
<hr/>

<a asp-action="Gft" asp-controller="wa" class="btn btn-outline-primary btn-lg btn-block">GFT's</a>
<hr/>

<a asp-action="Tecnologia" asp-controller="wa" class="btn btn-outline-danger btn-lg btn-block">Tecnologias</a>
<hr/>

<a asp-action="Projetos" asp-controller="wa" class="btn btn-outline-warning btn-lg btn-block">Projetos</a>

Views/wa/Projetos.cshtml
@model IEnumerable<desafio_mvc.Models.Projeto> 

@{
    Layout = "_Layout";
}

@* <script>
    function deleta(){
    var x;
    if (confirm("Deseja deletar?")) {
                     
        } else {   
                       
        }
        document.getElementById("demo").innerHTML=x;
    }
    </script> *@


<script>
    $(document).ready( function () {
    $('#projetos').DataTable({
        "language": {
            "lengthMenu" : "Mostrando _MENU_ registros por pagina",
            "zeroRecords":  "Nada encontrado, desculpa",
            "info" : "Mostrando pagina _PAGE_ de _PAGES_",
            "infoEmpty" : "Nenhum registro disponivel",
            "search":   "Buscar:",
            "paginate": {
                "first":    "Primeiro",
                "last":     "Ultimo",
                "next":     "Proximo",
                "previous": "Anterior"
            }
        }
    });
    });
</script>

<div class="container-sm text-center">
    <h2>Projetos cadastrados</h2>

    <a asp-action="CadastrarProjeto" asp-controller="wa" class="btn btn-outline-info">Cadastrar Projeto</a>
    <a asp-action="Vagas" asp-controller="wa" class="btn btn-outline-warning">Vagas</a>
    
    <hr/>

    @if (Model != null)
    {
        <table id="projetos" class="table table-striped table-bordered">
        <thead>
            <tr>
                <th>Nome </th>
                <th>Ações</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var proj in Model){
                <tr>
                    <td>@proj.Nome</td>
                    <td>
                        <a href="/wa/EditarProjeto/@proj.Id" class="btn btn-success">Editar</a>
                        
                        <button class="btn btn-danger" onclick="deleta()">Deletar</button>

                        <form asp-action="Deletar" asp-controller="Projeto" style="display: inline;">
                            <input type="hidden" name="id" id="id" value="@proj.Id">
                            <button id=deletar  type="hidden" class="btn btn-danger">Deletar</button>
                        </form>
                    </td>
                </tr>
            }
        </tbody>
    </table>
    }
    else {
        <h1>Nenhum projeto encontrado</h1>
    }
</div>